### PR TITLE
Upgrade password reset flow

### PR DESCRIPTION
**Pull request by LarsSelbekk**

### CODE REVIEW

**Comment by LarsSelbekk** [comment]
[Sikkerhetshull: kan endre hvem som helst sitt passord](https://trello.com/c/xkpYdkXG/812-sikkerhetshull-kan-endre-hvem-som-helst-sitt-passord)

**Comment by AdrianAndersen** [comment]
Update the text so that it says that it might have sent an email

**Comment by LarsSelbekk** [comment]
> Update the text so that it says that it might have sent an email

Done

**Comment by LarsSelbekk** [comment]
> Update the text so that it says that it might have sent an email

Done

**Review by AdrianAndersen — APPROVED** [review]

**Pull request merged**
